//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodify.Core.Resources {
    using System;
    using System.Reflection;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foodify.Core.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string Error_User_NotFound {
            get {
                return ResourceManager.GetString("Error_User_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to User created successfully..
        /// </summary>
        public static string Success_User_Created {
            get {
                return ResourceManager.GetString("Success_User_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to User updated successfully..
        /// </summary>
        public static string Success_User_Updated {
            get {
                return ResourceManager.GetString("Success_User_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully..
        /// </summary>
        public static string Success_User_Deleted {
            get {
                return ResourceManager.GetString("Success_User_Deleted", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order created successfully..
        /// </summary>
        public static string Success_Order_Created {
            get {
                return ResourceManager.GetString("Success_Order_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order not found..
        /// </summary>
        public static string Error_Order_NotFound {
            get {
                return ResourceManager.GetString("Error_Order_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order updated successfully..
        /// </summary>
        public static string Success_Order_Updated {
            get {
                return ResourceManager.GetString("Success_Order_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order deleted successfully..
        /// </summary>
        public static string Success_Order_Deleted {
            get {
                return ResourceManager.GetString("Success_Order_Deleted", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Restaurant created successfully..
        /// </summary>
        public static string Success_Restaurant_Created {
            get {
                return ResourceManager.GetString("Success_Restaurant_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Restaurant not found..
        /// </summary>
        public static string Error_Restaurant_NotFound {
            get {
                return ResourceManager.GetString("Error_Restaurant_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Restaurant updated successfully..
        /// </summary>
        public static string Success_Restaurant_Updated {
            get {
                return ResourceManager.GetString("Success_Restaurant_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Restaurant deleted successfully..
        /// </summary>
        public static string Success_Restaurant_Deleted {
            get {
                return ResourceManager.GetString("Success_Restaurant_Deleted", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order item created successfully..
        /// </summary>
        public static string Success_OrderItem_Created {
            get {
                return ResourceManager.GetString("Success_OrderItem_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order item not found..
        /// </summary>
        public static string Error_OrderItem_NotFound {
            get {
                return ResourceManager.GetString("Error_OrderItem_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order item updated successfully..
        /// </summary>
        public static string Success_OrderItem_Updated {
            get {
                return ResourceManager.GetString("Success_OrderItem_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Order item deleted successfully..
        /// </summary>
        public static string Success_OrderItem_Deleted {
            get {
                return ResourceManager.GetString("Success_OrderItem_Deleted", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Menu created successfully..
        /// </summary>
        public static string Success_Menu_Created {
            get {
                return ResourceManager.GetString("Success_Menu_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Menu not found..
        /// </summary>
        public static string Error_Menu_NotFound {
            get {
                return ResourceManager.GetString("Error_Menu_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Menu updated successfully..
        /// </summary>
        public static string Success_Menu_Updated {
            get {
                return ResourceManager.GetString("Success_Menu_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Menu deleted successfully..
        /// </summary>
        public static string Success_Menu_Deleted {
            get {
                return ResourceManager.GetString("Success_Menu_Deleted", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery partner created successfully..
        /// </summary>
        public static string Success_DeliveryPartner_Created {
            get {
                return ResourceManager.GetString("Success_DeliveryPartner_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery partner not found..
        /// </summary>
        public static string Error_DeliveryPartner_NotFound {
            get {
                return ResourceManager.GetString("Error_DeliveryPartner_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery partner updated successfully..
        /// </summary>
        public static string Success_DeliveryPartner_Updated {
            get {
                return ResourceManager.GetString("Success_DeliveryPartner_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery partner deleted successfully..
        /// </summary>
        public static string Success_DeliveryPartner_Deleted {
            get {
                return ResourceManager.GetString("Success_DeliveryPartner_Deleted", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery assignment created successfully..
        /// </summary>
        public static string Success_DeliveryAssignment_Created {
            get {
                return ResourceManager.GetString("Success_DeliveryAssignment_Created", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery assignment not found..
        /// </summary>
        public static string Error_DeliveryAssignment_NotFound {
            get {
                return ResourceManager.GetString("Error_DeliveryAssignment_NotFound", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery assignment updated successfully..
        /// </summary>
        public static string Success_DeliveryAssignment_Updated {
            get {
                return ResourceManager.GetString("Success_DeliveryAssignment_Updated", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Delivery assignment deleted successfully..
        /// </summary>
        public static string Success_DeliveryAssignment_Deleted {
            get {
                return ResourceManager.GetString("Success_DeliveryAssignment_Deleted", resourceCulture);
            }
        }
    }
}
